import { mkdir, writeFile } from 'node:fs/promises'
import { build } from 'esbuild'

const result = await build({
  entryPoints: ['server/dsh/bridge.ts'],
  outfile: 'dist/dsh-bridge.mjs',
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  sourcemap: false,
  legalComments: 'none',
  write: false,
})

const bridge = result.outputFiles.find(file => file.path.endsWith('/dsh-bridge.mjs'))
if (!bridge) throw new Error('esbuild did not produce dist/dsh-bridge.mjs')
await mkdir('dist', { recursive: true })
await writeFile('dist/dsh-bridge.mjs', bridge.contents)
await writeFile(
  'server/generated-bridge.ts',
  `// Generated by npm run build; do not edit.\nexport const DSH_BRIDGE_SOURCE = ${JSON.stringify(bridge.text)};\n`,
)
